=== jericbryledy/project-whirlpool/trunk/whirlpool.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.jericbryledy.com" targetNamespace="http://www.jericbryledy.com" elementFormDefault="qualified">
	<xs:element name="class" type="classType" />

	<xs:complexType name="classType">
		<xs:all>
			<xs:element name="name" type="xs:string" />
			<xs:element name="units" type="unitsType" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="unitsType">
		<xs:sequence>
			<xs:element name="unit" type="unitType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="unitType">
		<xs:all>
			<xs:element name="name" type="xs:string" />
			<xs:element name="lectures" type="lecturesType" />
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="lecturesType">
		<xs:sequence>
			<xs:element name="lecture" type="lectureType" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="lectureType">
		<xs:all>
			<xs:element name="name" type="xs:string" />
			<xs:element name="video" type="xs:string" />
			<xs:element name="question" type="questionType" minOccurs="0" />
		</xs:all>
		<xs:attribute name="id" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="questionType">
		<xs:all>
			<xs:element name="image" type="xs:string" />
			<xs:element name="form" type="formType" />
			<xs:element name="answers" type="answersType" />
			<xs:element name="explanation" type="xs:string" minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="formType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="text" type="textField" />
			<xs:element name="radio" type="radioType" />
			<xs:element name="checks" type="checksType" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="radioType">
		<xs:sequence>
			<xs:element name="choice" type="clickField" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="checksType">
		<xs:sequence>
			<xs:element name="check" type="clickField" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="answersType">
		<xs:sequence>
			<xs:element name="answer" type="answerType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="answerType">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="textField">
		<xs:complexContent>
			<xs:extension base="coordinatedField">
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="clickField">
		<xs:complexContent>
			<xs:extension base="coordinatedField">
				<xs:attribute name="value" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="coordinatedField">
		<xs:attribute name="x" type="xs:integer" use="required" />
		<xs:attribute name="y" type="xs:integer" use="required" />
	</xs:complexType>

</xs:schema>

=== jericbryledy/project-whirlpool/whirlpool-application/example-class.xml
<class xmlns="http://www.jericbryledy.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jericbryledy.com http://project-whirlpool.googlecode.com/files/whirlpool.xsd">
	<name>Example Class</name>
	<units>
		<unit id="01">
			<name>Unit 1</name>
			<lectures>
				<lecture id="01-01">
					<name>Lecture 1</name>
					<video>video-01-01.mp4</video>
					<question>
						<image>image-01-01.mp4</image>
						<form>
							<text x="10" y="10" name="q1" />
							<checks name="q2">
								<check x="10" y="30" value="a" />
								<check x="10" y="50" value="b" />
								<check x="10" y="70" value="c" />
							</checks>
							<radio name="q3">
								<choice x="10" y="90" value="d" />
								<choice x="10" y="110" value="e" />
								<choice x="10" y="130" value="f" />
							</radio>
						</form>
						<answers>
							<answer name="q1" value="hello" />
							<answer name="q2" value="a b" />
							<answer name="q3" value="e" />
						</answers>
						<explanation>video-01-01-exp.mp4</explanation>
					</question>
				</lecture>
			</lectures>
		</unit>
	</units>
</class>

=== jericbryledy/project-whirlpool/whirlpool-application/ai-class/ai-class.xml
<class xmlns="http://www.jericbryledy.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.jericbryledy.com ../../whirlpool.xsd">
	<name>Introduction to AI Class by Prof. Thrun and Prof. Norvig</name>
	<units>
		<unit id="00">
			<name>Example Unit (for testing Purpose only)</name>
			<lectures>
				<lecture id="00-00">
					<name>Example Lecture (for testing Purpose only)</name>
					<video>ai-class/ai-res/01-02.mp4</video>
					<question>
						<image>ai-class/ai-res/01-02.jpg</image>
						<form>
							<radio name="q1">
								<choice x="126" y="208" value="wetware" />
								<choice x="127" y="268" value="formula" />
								<choice x="127" y="326" value="intelligent_agent" />
							</radio>
							<radio name="q2">
								<choice x="10" y="10" value="wetware" />
								<choice x="50" y="50" value="formula" />
								<choice x="100" y="100" value="intelligent_agent" />
							</radio>
							<text name="q3" x="200" y="10" />
							<checks name="q4">
								<check value="test" x="10" y="200" />
							</checks>
						</form>
						<answers>
							<answer name="q1" value="intelligent_agent" />
							<answer name="q2" value="formula" />
							<answer name="q3" value="hello" />
							<answer name="q4" value="test" />
						</answers>
						<explanation>ai-class/ai-res/01-02-exp.mp4</explanation>
					</question>
				</lecture>
			</lectures>
		</unit>
		<unit id="01">
			<name>Welcome to AI</name>
			<lectures>
				<lecture id="01-01">
					<name>Introduction</name>
					<video>ai-class/ai-res/01-01.mp4</video>
				</lecture>
				<lecture id="01-02">
					<name>Course Overview</name>
					<video>ai-class/ai-res/01-02.mp4</video>
					<question>
						<image>ai-class/ai-res/01-02.jpg</image>
						<form>
							<radio name="q1">
								<choice x="118" y="200" value="wetware" />
								<choice x="118" y="261" value="formula" />
								<choice x="122" y="319" value="intelligent_agent" />
							</radio>
						</form>
						<answers>
							<answer name="q1" value="intelligent_agent" />
						</answers>
					</question>
				</lecture>
				<lecture id="01-03">
					<name>Intelligent Agents</name>
					<video>ai-class/ai-res/01-03.mp4</video>
					<question>
						<image>ai-class/ai-res/01-03.jpg</image>
						<form>
							<checks name="q1">
								<check value="finance" x="131" y="107" />
								<check value="robotics" x="129" y="140" />
								<check value="games" x="126" y="171" />
								<check value="medicine" x="125" y="207" />
								<check value="theweb" x="122" y="244" />
								<check value="none" x="124" y="281" />
							</checks>
						</form>
						<answers>
							<answer name="q1" value="finance robotics games medicine theweb" />
						</answers>
					</question>
				</lecture>
				<lecture id="01-04">
					<name>Applications of AI</name>
					<video>ai-class/ai-res/01-04.mp4</video>
				</lecture>
				<lecture id="01-05">
					<name>Terminology</name>
					<video>ai-class/ai-res/01-05.mp4</video>
					<question>
						<image>ai-class/ai-res/01-05.jpg</image>
						<form>
							<checks name="checkers">
								<check x="211" y="222" value="partially_observable" />
								<check x="339" y="216" value="stochastic" />
								<check x="459" y="214" value="continuous" />
								<check x="578" y="217" value="adversarial" />
							</checks>
						</form>
						<answers>
							<answer name="checkers" value="adversarial" />
						</answers>
						<explanation>ai-class/ai-res/01-05-exp.mp4</explanation>
					</question>
				</lecture>
				<lecture id="01-06">
					<name>Poker Question</name>
					<video>ai-class/ai-res/01-06.mp4</video>
					<question>
						<image>ai-class/ai-res/01-06.jpg</image>
						<form>
							<checks name="poker">
								<check x="200" y="247" value="partially_observable" />
								<check x="317" y="245" value="stochastic" />
								<check x="424" y="240" value="continuous" />
								<check x="533" y="240" value="adversarial" />
							</checks>
						</form>
						<answers>
							<answer name="poker" value="partially_observable stochastic adversarial" />
						</answers>
						<explanation>ai-class/ai-res/01-06-exp.mp4</explanation>
					</question>
				</lecture>
				<lecture id="01-07">
					<name>Robot Car Question</name>
					<video>ai-class/ai-res/01-07.mp4</video>
					<question>
						<image>ai-class/ai-res/01-07.jpg</image>
						<form>
							<checks name="robot">
								<check x="196" y="295" value="partially_observable" />
								<check x="315" y="285" value="stochastic" />
								<check x="426" y="283" value="continuous" />
								<check x="533" y="280" value="adversarial" />
							</checks>
						</form>
						<answers>
							<answer name="robot" value="partially_observable stochastic continuous" />
						</answers>
						<explanation>ai-class/ai-res/01-07-exp.mp4</explanation>
					</question>
				</lecture>
				<lecture id="01-08">
					<name>AI and Uncertainty</name>
					<video>ai-class/ai-res/01-08.mp4</video>
				</lecture>
				<lecture id="01-09">
					<name>Machine Translation</name>
					<video>ai-class/ai-res/01-09.mp4</video>
					<question>
						<image>ai-class/ai-res/01-09.jpg</image>
						<form>
							<checks name="chicken">
								<check x="77" y="72" value="57-1" />
								<check x="140" y="72" value="57-2" />
								<check x="74" y="113" value="58-1" />
								<check x="123" y="114" value="58-2" />
								<check x="74" y="134" value="59-1" />
								<check x="167" y="134" value="59-2" />
								<check x="142" y="176" value="61" />
								<check x="168" y="218" value="63" />
								<check x="71" y="237" value="64" />
								<check x="119" y="259" value="65" />
								<check x="168" y="282" value="66" />
								<check x="72" y="299" value="67-1" />
								<check x="136" y="301" value="67-2" />
								<check x="72" y="322" value="68-1" />
								<check x="147" y="322" value="68-2" />
								<check x="71" y="345" value="69-1" />
								<check x="166" y="344" value="69-2" />
							</checks>
						</form>
						<answers>
							<answer name="chicken" value="57-2 58-1 59-1 67-1" />
						</answers>
					</question>
				</lecture>
				<lecture id="01-10">
					<name>Chinese Translation 1</name>
					<video>ai-class/ai-res/01-10.mp4</video>
					<question>
						<image>ai-class/ai-res/01-10.jpg</image>
						<form>
							<checks name="corn_cream">
								<check x="121" y="116" value="58" />
								<check x="122" y="135" value="59-1" />
								<check x="161" y="135" value="59-2" />
								<check x="79" y="157" value="60-1" />
								<check x="107" y="156" value="60-2" />
								<check x="124" y="195" value="62-1" />
								<check x="161" y="197" value="62-2" />
								<check x="71" y="217" value="63-1" />
								<check x="160" y="217" value="63-2" />
								<check x="120" y="259" value="65-1" />
							</checks>
						</form>
						<answers>
							<answer name="corn_cream" value="67-1 67-2 68-2 68-3" />
						</answers>
					</question>
				</lecture>
			</lectures>
		</unit>
<!--		<unit id="02">
			<name>Problem Solving</name>
		</unit>-->
	</units>
</class>
